### ISSUE TITLE
ITK Python wrapping problem?

### ISSUE THREAD

**Issue by melrobin** [InsightSoftwareConsortium/itk-jupyter-widgets#108]
I am trying to run the examples from the Introduction of the Kitware course located here:
https://data.kitware.com/#collection/568a9db98d777f429eac8eab/folder/5b0bfb858d777f15ebe1fa62

Essentially I am using the following code:
import itk
from itkwidgets import view
file_name='./brainweb165a10f17.mha'
image=itk.imread(file_name, pixelType=itk.ctype('float'))
view(image)

This fails with the following traceback:
file_name='./brainweb165a10f17.mha'

image=itk.imread(file_name, pixelType=itk.ctype('float'))

view(image)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-19fc82cf36db> in <module>()
      1 file_name='./brainweb165a10f17.mha'
      2 image=itk.imread(file_name, pixelType=itk.ctype('float'))
----> 3 view(image)

/usr/lib/python2.7/site-packages/itkwidgets/widget_viewer.pyc in view(image, ui_collapsed, annotations, interpolation, cmap, mode, shadow, slicing_planes, gradient_opacity, **kwargs)
    436             annotations=annotations, interpolation=interpolation, cmap=cmap,
    437             mode=mode, shadow=shadow, slicing_planes=slicing_planes,
--> 438             gradient_opacity=gradient_opacity, **kwargs)
    439     return viewer

/usr/lib/python2.7/site-packages/itkwidgets/widget_viewer.pyc in __init__(self, **kwargs)
    226             self.extractor.InPlaceOn()
    227             self.shrinker = itk.BinShrinkImageFilter.New(self.extractor)
--> 228         self._update_rendered_image()
    229         if self._downsampling:
    230             self.observe(self._on_roi_changed, ['roi'])

/usr/lib/python2.7/site-packages/itkwidgets/widget_viewer.pyc in _update_rendered_image(self)
    309                 return
    310 
--> 311             self.shrinker.UpdateLargestPossibleRegion()
    312             if is_largest:
    313                 self._largest_roi_rendered_image = self.shrinker.GetOutput()

RuntimeError: /home/melrobin/packages/ITK/Modules/Core/Common/src/itkProcessObject.cxx:1412:
itk::ERROR: BinShrinkImageFilter(0x55ad7d7646d0): Input Primary is required but not set.

I started debugging the Python end of things and all seems to work well so my thoughts are that there might be a problem in instantiating this object and making sure that two template parameters are specified, but I'm not sure where to look from there.  See this class documentation:

https://itk.org/Doxygen47/html/classitk_1_1BinShrinkImageFilter.html

I cannot make any further progress, but can work on it with more suggestions.

**Comment by melrobin** [comment]
I did run check_env.ipynb and got this traceback, but I do not think that this is related:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-329b9299a2d5> in <module>()
     61 # now the dependencies
     62 for lib, required_version in list(requirements.items()):
---> 63     import_version(lib, required_version)

<ipython-input-1-329b9299a2d5> in import_version(pkg, min_ver, fail_msg)
     26         mod = importlib.import_module(pkg)
     27         if pkg in {'itk'}:
---> 28             ver = mod.Version.GetITKVersion()
     29         else:
     30             ver = mod.__version__

AttributeError: module 'itk' has no attribute 'Version'

**Comment by melrobin** [comment]
I did run check_env.ipynb and got this traceback, but I do not think that this is related:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-329b9299a2d5> in <module>()
     61 # now the dependencies
     62 for lib, required_version in list(requirements.items()):
---> 63     import_version(lib, required_version)

<ipython-input-1-329b9299a2d5> in import_version(pkg, min_ver, fail_msg)
     26         mod = importlib.import_module(pkg)
     27         if pkg in {'itk'}:
---> 28             ver = mod.Version.GetITKVersion()
     29         else:
     30             ver = mod.__version__

AttributeError: module 'itk' has no attribute 'Version'

**Comment by thewtex** [comment]
@melrobin how did you install ITK, and what version of ITK are you using?

If you try this from a Python terminal

```
$ python
>>> import itk
>>> itk.Version.GetITKVersion()
```

what is returned?

**Comment by melrobin** [comment]
It returns version 4.13.0, but I built ITK from development sources.  
>>> itk.Version.GetITKVersion()
'4.13.0'

I might have a couple of versions inadvertently installed on my machine and will check this.

**Comment by melrobin** [comment]
Oh, BTW, should its.Version.GetITKVersion() read 5.0 if building from development sources?

**Comment by thewtex** [comment]
> It returns version 4.13.0, but I built ITK from development sources.

> I might have a couple of versions inadvertently installed on my machine and will check this.

4.13.0 should be sufficient -- it sounds like there may be some contamination of Python environments.

A good practice is to work in a [Python virtual environment](https://realpython.com/python-virtual-environments-a-primer/). This will isolate packages and may fix your issue. Please give it a try and let us know how it goes.

> Oh, BTW, should its.Version.GetITKVersion() read 5.0 if building from development sources?

If using ITK Git `master`, yes.

**Comment by melrobin** [comment]
You're right.  There is some cruft in my environment.  The version still reads 4.13.0, but I should be able to clean this up.  Thanks for your help!
