### ISSUE TITLE
Create conda forge package.

### ISSUE THREAD

**Issue by hadim** [InsightSoftwareConsortium/itk-jupyter-widgets#109]
Create conda forge package.

**Comment by hadim** [comment]
See https://github.com/conda-forge/staged-recipes/pull/7104

**Comment by hadim** [comment]
Here is a fix I had to patch from the source tarball: 

```diff
diff --git a/setup.py b/setup.py
index 2e3f282..176b17e 100644
--- a/setup.py
+++ b/setup.py
@@ -69,8 +69,7 @@ class NPM(Command):

     targets = [
         os.path.join(here, 'itkwidgets', 'static', 'extension.js'),
-        os.path.join(here, 'itkwidgets', 'static', 'index.js'),
-        os.path.join(here, 'js', 'dist', 'labextension.js')
+        os.path.join(here, 'itkwidgets', 'static', 'index.js')
     ]

     def initialize_options(self):
```

Without this, the Conda build failed because the  `.js/` folder is missing.

**Comment by hadim** [comment]
@thewtex feel free if you want to backport it to `master`.

**Comment by thewtex** [comment]
@hadim thanks for taking the lead on the conda-forge package! :clap: I am not a conda expert, but I will help as I can.

Your changes for the sdist are added: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/110

**Comment by hadim** [comment]
It's now on conda forge.
