### ISSUE TITLE
Add JupyterLab widget support

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itk-jupyter-widgets#11]
Enable JupyterLab extension support per:

  https://github.com/jupyter-widgets/widget-cookiecutter/pull/31/files
  https://github.com/jupyter-widgets/widget-cookiecutter/pull/32/files
  https://github.com/jupyter-widgets/widget-cookiecutter/pull/33/files
  https://github.com/jupyter-widgets/widget-cookiecutter/pull/34/commits/18cad9b6b42c8ea48338a2020e27afb136657fb5
  https://github.com/jupyter-widgets/widget-cookiecutter/pull/35/files

Document how to enable the extension per:

 https://ipywidgets.readthedocs.io/en/latest/user_install.html

Add `jupyterlab-extension` to the list of GitHub topics for the repository.

**Comment by jeffbaumes** [comment]
FWIW I found the Vega extension to be a great use minimal use case for creating a mime type and registering file extensions.

https://github.com/jupyterlab/jupyterlab/tree/master/packages/vega3-extension

**Comment by thewtex** [comment]
Nice! Thanks, @jeffbaumes !

**Comment by thewtex** [comment]
All the `jupyterlab-extension` infrastructure is there, as far I can tell. However, we need to way to tell the JupyterLab extension infrastructure to use the Webpack Rules and Plugins that we need.

**Comment by thewtex** [comment]
xref https://github.com/jupyterlab/jupyterlab/issues/4328

CC: @johnkit

**Comment by saulshanabrook** [comment]
> However, we need to way to tell the JupyterLab extension infrastructure to use the Webpack Rules and Plugins that we need.

Which particular rules and plugins are these? You might be able to transform first with your existing webpack setup and then use that output for the jupyterlab plugin.

**Comment by thewtex** [comment]
@saulshanabrook 

These are the rules:

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/8b650ad3604fea6215c0cc7ff7eeb314d02f4d10/js/webpack.config.js#L6-L25

and this plugin:

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/8b650ad3604fea6215c0cc7ff7eeb314d02f4d10/js/webpack.config.js#L88-L102
