### ISSUE TITLE
Check out pyimagej 0.4.0

### ISSUE THREAD

**Issue by ctrueden** [InsightSoftwareConsortium/itk-jupyter-widgets#116]
With the 0.4.0 release of the ImageJ Python module—renamed from `imagej` to `pyimagej` now—it is feasible to start up an ImageJ without needing a local copy of Fiji:
```python
import imagej
ij = imagej.init()
```
By default, it grabs the latest release of the `net.imagej:imagej` artifact from the maven.imagej.net.

You can also spin up a different version explicitly for reproducibility, or spin up an ImageJ1-enabled ImageJ, or a full Fiji installation. See the [README](https://github.com/imagej/pyimagej/blob/68738c0f633f07e4c6d74591a68b2e56cacfc0dc/README.md#creating-the-imagej-gateway) for details.

One of these capabilities may help streamline relevant ImageJ usage in example notebooks here.

I did some testing but there are surely still some rough edges. If you get a chance to play with it and find any issues, please do not hesitate to let me know.

The release is available now on PyPI, and should be on conda-forge as well shortly.

**Comment by VolkerH** [comment]
I just checked it out and am curious. Does `pyimagej` provide a way to convert to numpy or do I need `imglyb` on top of that.
Maybe not the right place to ask here (given these are the issues for itk-jupyter-widgets, in fact I was surprised to see the announcment here), would be happy to move this discussion elsewhere if desired.

**Comment by ctrueden** [comment]
The package on PyPI and conda-forge is now called `pyimagej` rather than `imagej`. This was done at the request of one of the conda-forge community maintainers, to avoid confusion with a theoretical future `imagej` conda package that would really just install an ImageJ application distribution, as opposed to the Python+Maven-based bootstrapping done by `pyimagej`. Perhaps we should delete the `imagej` package on PyPI to avoid confusion?

Regarding imglyb: it is now an encapsulated dependency of pyimagej, so you should not need to use it explicitly anymore. Instead of `imglyb.to_imglyb` you can now write `ij.py.to_java(...)` and a variety of types are supported including numpy images, collections (dict, set, list, iterable, iterator), strings and primitives. (Leaning on the new [scyjava conversion logic](https://github.com/scijava/scyjava/#available-functions).) There is also `ij.py.from_java(...)` for going from Java back to Python.

If you can install pyimagej via conda, I think that is easiest, since the dependencies should all be in order on the conda-forge channel now. I just tested on a headless Ubuntu 18.04 LTS server using miniconda:
```
$ conda create -y -c conda-forge -n imagej pyimagej scikit-image
...
$ source activate pyimagej
$ python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
...
2.0.0-rc-68
```

There was one bug with matplotlib and qt on that system, which I fixed on the master branch (imagej/pyimagej@05a1a501935beddfcb5b604f3ae7ede34b9e2a70).

If you want to use pip instead, that should also work. You will need `java`, `gcc` and `maven` available on the system. You will also need to set `JAVA_HOME`. The following worked on my headless Ubuntu system:
```
$ sudo apt install build-essential openjdk-8-jdk maven
...
$ conda create -y -n pip-imagej python=3.7
...
$ source activate pip-imagej
$ pip install pyimagej
$ export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
$ python -c 'import imagej; ij = imagej.init(); print(ij.getVersion())'
...
2.0.0-rc-68
```
NB: The first time I went through this process, I did `pip install cython` and `pip install pyjnius` and cython was used to compile pyjnius. I then wiped my conda environment, ran `conda clean --all`, and ran it again with only `pip install pyimagej` to make sure it would work cleanly, and everything ran much faster with no local compilation and lots of "Using cached https://files.pythonhosted.org/packages..." messages. So I'm not sure what will happen on your system; let me know if issues!

@VolkerH wrote:
> Maybe not the right place to ask here (given these are the issues for itk-jupyter-widgets, in fact I was surprised to see the announcment here), would be happy to move this discussion elsewhere if desired.

Yeah, I have not had a chance to formally announce the release yet; will try to do so later today or tomorrow. It was not my goal to hijack this issue tracker—just wanted to give @thewtex a heads up about the new pyimagej release. The [Image.sc Forum](https://forum.image.sc/) would be a better place to discuss at length.

> Does pyimagej provide a way to convert to numpy or do I need imglyb on top of that?

In general, you cannot convert from ImgLib2 to numpy, because ImgLib2 is interface driven and numpy is not. Instead, the pattern is to create a numpy image, and wrap that to a Java ImgLib2 image. Then populate the ImgLib2 data on the Java side. If you have an image created on the Java side, copy it onto an image wrapped from numpy.

Example notebook prototype [here](https://github.com/imagej/i2k-2018) (unfinished; and no promises that link will keep working permanently). I will also give a workshop at I2K later this week.

**Comment by thewtex** [comment]
@ctrueden very nice!

It sounds like the easiest cross-platform path for folks will be conda-forge. 

I started to up the example here, testing with a fresh conda environment:

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/701f5dd7bba32771ccbd76f0c0db31d6832196cd/examples/ImageJImgLib2.ipynb

`import imagej` is resulting in the error  `Unable to import scyjava: PYJNIUS_JAR environment variable not defined.` Any ideas?

CC: @hadim

**Comment by ctrueden** [comment]
@thewtex I'm on a mobile device on an airplane about to take off, so cannot easily double check now, but IIRC, there is an environment activation script that sets that variable. How does one accomplish `source activate` from a notebook? If it cannot be done easily, I can look into detecting the value in python code somehow; I think it would be ideal if the activation script(s) was not needed.

In the meantime, you could `source activate` an equivalent environment from the CLI and then check the value of the variable.

**Comment by hadim** [comment]
Yes it looks like an activation error: https://github.com/conda-forge/pyjnius-feedstock/blob/680b7f432340bad14be477bead82e6eacf863799/recipe/activate.sh

You need somehow to run that script in order to set `PYJNIUS_JAR`.

@ctrueden `scyjava` could try to be smart about it: https://github.com/scijava/scyjava/blob/8142d4117e448c881789a9ba553241fc5de9b215/scyjava/__init__.py#L26. It could check for regular path such as `$PREFIX/share/pyjnius/pyjnius.jar` on Linux and fallback to env variable if it failed (or maybe favor the env variable first and then fallback).

**Comment by thewtex** [comment]
@hadim that gets us closer:

```
os.environ['PYJNIUS_JAR'] = os.path.join(sys.prefix, "share", "pyjnius", "pyjnius.jar")
os.environ['JAVA_HOME']  = sys.prefix

import imagej
```

now succeeds.  But,

```
ij = imagej.init()
```

results in:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-e33202d8e4de> in <module>
      1 # Initialize imagej
----> 2 ij = imagej.init()
      3 print(ij.getVersion())

~/bin/miniconda3/envs/imagej/lib/python3.6/site-packages/imagej/imagej.py in init(ij_dir_or_version_or_endpoint, headless)
     73 
     74     if headless:
---> 75         scyjava_config.add_options('-Djava.awt.headless=true')
     76 
     77     if ij_dir_or_version_or_endpoint is None:

~/bin/miniconda3/envs/imagej/lib/python3.6/site-packages/scyjava_config.py in add_options(*opts)
    112 
    113 def add_options(*opts):
--> 114     jnius_config.add_options(*opts)
    115 
    116 

~/bin/miniconda3/envs/imagej/lib/python3.6/site-packages/jnius_config.py in add_options(*opts)
     25     "Appends options to the list of VM options."
     26     if vm_running:
---> 27         raise ValueError("VM is already running, can't set options")
     28     global options
     29     options.extend(opts)

ValueError: VM is already running, can't set options
```

**Comment by hadim** [comment]
Try to restart your notebook.

**Comment by thewtex** [comment]
> Try to restart your notebook.

Persists across starts :-(

**Comment by VolkerH** [comment]
Just gave it a try in a clean conda-environment on Windows. I get what I assume is a maven error message about `failing to bootstrap the artifact`. I wonder whether some of the suggested `.jgorc` repositories are in your home directory so you wouldn't have this issue?

```
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imagej
>>> ij  = imagej.init()
INFO 2018-12-04 16:13:19,772: Failed to bootstrap the artifact.
INFO 2018-12-04 16:13:19,772:
INFO 2018-12-04 16:13:19,777: Possible solutions:
INFO 2018-12-04 16:13:19,789: * Double check the endpoint for correctness (https://search.maven.org/).
INFO 2018-12-04 16:13:19,791: * Add needed repositories to ~/.jgorc [repositories] block (see README).
INFO 2018-12-04 16:13:19,792: * Try with an explicit version number (release metadata might be wrong).

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\imagej\imagej.py", line 104, in init
    import imglyb
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\imglyb\__init__.py", line 41, in <module>
    config, _ = _init_jvm_options()
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\imglyb\__init__.py", line 36, in _init_jvm_options
    import scyjava
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\scyjava\__init__.py", line 55, in <module>
    jnius = _init_jvm()
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\scyjava\__init__.py", line 41, in _init_jvm
    verbose=scyjava_config.get_verbose()
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\jgo\jgo.py", line 426, in resolve_dependencies
    raise e
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\jgo\jgo.py", line 417, in resolve_dependencies
    mvn_out = run_and_combine_outputs(mvn, *mvn_args)
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\site-packages\jgo\jgo.py", line 185, in run_and_combine_outputs
    return subprocess.check_output((command,) + args, stderr=subprocess.STDOUT)
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\Volker\Anaconda3\envs\imagej\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('C:\\Users\\Volker\\Anaconda3\\envs\\imagej\\Library\\bin\\mvn.CMD', '-B', '-f', 'C:\\Users\\Volker\\.jgo\\net\\imagej\\imagej\\RELEASE+net.imglib-imglib2-imglyb-0.3.0\\pom.xml', 'dependency:resolve')' returned non-zero exit status 1.
>>>
```

**Comment by hadim** [comment]
@thewtex does the conda package work when you `source activate` it from a terminal and then do `python -c "ij = imagej.init()"`? Or the error only happens in the notebook?

**Comment by hadim** [comment]
Also, the error seems to be related to the order you load the libs. IJ initialization can only be done on time so you must import `imagej` first before any scyjava/jnius imports.

For me the following works:

```bash
conda create -n test pyimagej
conda activate test
python -c "import imagej;ij = imagej.init()"
```

(except an error related to `matplotlib`, I will rebuild `pyimagej` and add `matplotlib` as a dep.)

**Comment by thewtex** [comment]
@hadim yes, this works for me:

```
source activate imagej
python -c "import imagej;ij = imagej.init()"
```

Maybe the package could be made more robust by setting the environment variables with `os.environ` and using the default provided by conda if not set. Also adding or shuffling import order so user import order does not cause errors...

**Comment by hadim** [comment]
@VolkerH looks like the conda package on Windows is broken: https://ci.appveyor.com/project/conda-forge/pyimagej-feedstock/builds/20849591/job/944eqo2bcpqcb6mq

Will pursue the discussion at https://github.com/conda-forge/pyimagej-feedstock/pull/3

**Comment by thewtex** [comment]
> I agree that would be a nice improvement. Could you open an issue on the `pyimagej` repo?

Yes! Added with a minimal example here: https://github.com/imagej/pyimagej/issues/21

**Comment by ctrueden** [comment]
Closing this issue here in favor of imagej/pyimagej#21 and scijava/scyjava#5. Once those are resolved, and I'm confident pyimagej is usable in a dynamic notebook context via `!` syntax, we can try again to update the notebooks here.
