### ISSUE TITLE
No widget displayed if view is called within an if block

### ISSUE THREAD

**Issue by daniellepace** [InsightSoftwareConsortium/itk-jupyter-widgets#125]
Thanks for this great project!

I've run into a strange behaviour:

`itkwidgets.view(v)`

works fine, but

```
if True:
    itkwidgets.view(v)
```

doesn't show anything.

My use case: I have a jupyter notebook that I use for interactive development (in which case I want to be able to visualize results), and then use nb_convert to create python scripts that I run on our cluster once the code is finalized. So, when running on the cluster I want to disable visualization code.

**Comment by thewtex** [comment]
> Thanks for this great project!

Thanks for the kind words, @daniellepace :-)



> ```
> if True:
>     itkwidgets.view(v)
> ```
> doesn't show anything.



> `itkwidgets.view(v)`
> 
> works fine,

A few things are happening here implicitly that may not be immediately obvious. `itkwidgets.view` returns a `Viewer` object. And, the IPython Jupyter kernel displays the last return value of a cell by default.

So,

```
from IPython.display import display
if True:
    display(itkwidgets.view(v))
```

or 

```
from IPython.display import display
if True:
    viewer = itkwidgets.view(v)
    display(viewer)
```

should do the trick.

**Comment by daniellepace** [comment]
Ah, I see! It works now, thanks very much!
