### ISSUE TITLE
PolyData: is it possible?

### ISSUE THREAD

**Issue by banesullivan** [InsightSoftwareConsortium/itk-jupyter-widgets#133]
Is it possible to display `vtkPolyData`? 

In the [`vtki` demo notebook](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/master/examples/vtki.UniformGrid.ipynb), the volume is sliced on planes. Are those slices `vtkPolyData`? How were those added?

This is related to https://github.com/Kitware/vtk-js/issues/991

> I'm eager to see `vtkPolyData` (`vtki.PolyData`) be supported by itk-jupyter-widgets; as for most cases, I'm comfortable applying a `vtkExtractGeometry` filter and displaying that in the VTKjs rendering rather than an entire mesh dataset. From the description you provided on how you transfer the data, I think vtki objects would provide a major benefit! vtki has much (if not all) the needed infrastructure for direct NumPy interfacing with the VTK objects.

**Comment by thewtex** [comment]
> In the [`vtki` demo notebook](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/master/examples/vtki.UniformGrid.ipynb), the volume is sliced on planes. Are those slices `vtkPolyData`? How were those added?

These are visualizations are generated for image data, e.g. `vtkImageData`.

`vtkPolyData` is next on my to-do list for the widgets. I am working on a few backend infrastructure pieces that we will bring into this repository. See also #112

**Comment by banesullivan** [comment]
Apologies for duplicating #112
