### ISSUE TITLE
Install from source fails ItkVtkViewer.module.css

### ISSUE THREAD

**Issue by WesleyTheGeolien** [InsightSoftwareConsortium/itk-jupyter-widgets#134]
Hi, 

I have been trying to run from source. I have followed the instructions at the bottom of the readme. I created a new conda enviroment to run in. 

When running `pip install -e .` I get:
```
ERROR in ./node_modules/itk-vtk-viewer/src/userInterface/ItkVtkViewer.module.css (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/postcss-loader/src??ref--11-2!./node_modules/itk-vtk-viewer/src/userInterface/ItkVtkViewer.module.css)
        Module build failed (from ./node_modules/css-loader/dist/cjs.js):
        CssSyntaxError
    
        (471:2) Expected a pseudo-class or pseudo-element.
    
          469 | }
          470 |
        > 471 | .fullscreenContainer: {
              |  ^
          472 |   position: absolute;
          473 |   width: 100vw;
```

Changing `.fullscreenContainer: {` manually in the file to `.fullscreenContainer {` allows the `pip install -e .` to complete.

Is anyone aware where the source of the problem is?

**Comment by thewtex** [comment]
@WesleyTheGeolien good catch!

Addressed upstream here: https://github.com/Kitware/itk-vtk-viewer/pull/135

**Comment by WesleyTheGeolien** [comment]
Awesome thanks @thewtex
