### ISSUE TITLE
I found it to be too hard to see the volume button

### ISSUE THREAD

**Issue by consideRatio** [InsightSoftwareConsortium/itk-jupyter-widgets#139]
Thanks for developing very exciting stuff and making it open source! Wow!!

The volume button, to the right of the three buttons for looking from three different sides, was very hard for me to visually spot. I found it by clicking on it by mistake and then realized there was a faint picture of a 3d box mesh.

It would be an improvement to make it more visible against its background in various situations.

![image](https://user-images.githubusercontent.com/3837114/56892116-e44a2a00-6a7e-11e9-8a89-abca673b24fc.png)
_It was very hard to spot it here._

![image](https://user-images.githubusercontent.com/3837114/56892298-8407b800-6a7f-11e9-90f1-51a3c457d775.png)
_It was easier to spot it here._

> **NOTE:** I'm not confident I'm writing this issue in the right repo, just tell me and I can move it.

**Comment by consideRatio** [comment]
Oh this was fixed?

![image](https://user-images.githubusercontent.com/3837114/57295537-0d943700-70cb-11e9-8ad8-99082e6364d4.png)

**Comment by thewtex** [comment]
@consideRatio thanks for giving the project a try and the kind feedback!

Thanks for the report. The blue faces to the volume rendering icon were added a while ago. Maybe this was related to a browser upgrade?

**Comment by consideRatio** [comment]
@thewtex hmmm perhaps, I can't tell if there has been a browser upgrade, I'll close this issue for now as I cannot even reproduce it any more and is actually looking great currently.

Praise comes easy for really awesome stuff ;)
