### ISSUE TITLE
Fail in JupyterLab

### ISSUE THREAD

**Issue by jxchen01** [InsightSoftwareConsortium/itk-jupyter-widgets#146]
Hello,

On a windows 10 machine, I created a clean conda environment. Then I only `pip install jupyterlab` and `pip install itkwidgets`. Also `conda install -c conda-forge nodejs`. Finally, I did `jupyter labextension install @jupyter-widgets/jupyterlab-manager itk-jupyter-widgets`

This should be a simple test on jupyterlab. But, the following test still failed. Any thoughts or suggestions?

```
from itkwidgets import view
import numpy as np
im = np.ones((30,100,100), dtype=np.uint8)
view(im)
```

Error message: `Error displaying widget`

`conda list` returns
# Name                    Version                   Build  Channel
attrs                     19.1.0                    <pip>
backcall                  0.1.0                     <pip>
bleach                    3.1.0                     <pip>
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3                    <pip>
colorama                  0.4.1                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.4.0                     <pip>
defusedxml                0.6.0                     <pip>
entrypoints               0.3                       <pip>
ipydatawidgets            4.0.0                     <pip>
ipykernel                 5.1.1                     <pip>
ipympl                    0.2.1                     <pip>
ipython                   7.5.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.4.2                     <pip>
itk-core                  5.0.0.post1               <pip>
itk-filtering             5.0.0.post1               <pip>
itk-numerics              5.0.0.post1               <pip>
itkwidgets                0.16.3                    <pip>
jedi                      0.14.0                    <pip>
Jinja2                    2.10.1                    <pip>
jsonschema                3.0.1                     <pip>
jupyter-client            5.2.4                     <pip>
jupyter-core              4.5.0                     <pip>
jupyterlab                0.35.6                    <pip>
jupyterlab-server         0.2.0                     <pip>
kiwisolver                1.1.0                     <pip>
MarkupSafe                1.1.1                     <pip>
matplotlib                3.1.0                     <pip>
mistune                   0.8.4                     <pip>
nbconvert                 5.5.0                     <pip>
nbformat                  4.4.0                     <pip>
nodejs                    11.14.0                       1    conda-forge
notebook                  5.7.8                     <pip>
numpy                     1.16.4                    <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.5.0                     <pip>
pickleshare               0.7.5                     <pip>
pip                       19.1.1                   py36_0
prometheus-client         0.7.1                     <pip>
prompt-toolkit            2.0.9                     <pip>
pycparser                 2.19                      <pip>
Pygments                  2.4.2                     <pip>
pyparsing                 2.4.0                     <pip>
pyrsistent                0.15.2                    <pip>
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.0                     <pip>
pywinpty                  0.5.5                     <pip>
pyzmq                     18.0.1                    <pip>
scipy                     1.3.0                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                41.0.1                   py36_0
six                       1.12.0                    <pip>
sqlite                    3.28.0               he774522_0
terminado                 0.8.2                     <pip>
testpath                  0.4.2                     <pip>
tornado                   6.0.2                     <pip>
traitlets                 4.3.2                     <pip>
traittypes                0.2.1                     <pip>
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.33.4                   py36_0
widgetsnbextension        3.4.2                     <pip>
wincertstore              0.2              py36h7fe50ca_0
zstandard                 0.11.1                    <pip>

**Comment by thewtex** [comment]
More information from the browser console (Ctrl + Shift + I to open), or the Python console would be helpful.

**Comment by jxchen01** [comment]
I am using Chrome.

There is no error in the Python console. 

```
[I 18:36:31.362 LabApp] Node v11.14.0

[I 18:36:40.305 LabApp] Build is up to date
[I 18:36:49.503 LabApp] Kernel started: 34b7665c-61ac-466c-9ef6-93b254ea93ac
[I 18:36:58.474 LabApp] Adapting to protocol v5.1 for kernel 34b7665c-61ac-466c-9ef6-93b254ea93ac
[I 18:36:58.474 LabApp] Adapting to protocol v5.1 for kernel 34b7665c-61ac-466c-9ef6-93b254ea93ac
[I 18:36:58.516 LabApp] Adapting to protocol v5.1 for kernel 34b7665c-61ac-466c-9ef6-93b254ea93ac
```

There are quite a few errors in the browers. 

```
default.js:64 Starting WebSocket: ws://localhost:8888/api/kernels/34b7665c-61ac-466c-9ef6-93b254ea93ac
3default.js:1428 Kernel: connected (34b7665c-61ac-466c-9ef6-93b254ea93ac)
default.js:924 Exception opening new comm
(anonymous) @ default.js:924
default.js:132 Error: Object 'jupyter.widget' not found in registry
    at default.js:1472
    at new Promise (<anonymous>)
    at Object.loadObject (default.js:1451)
    at DefaultKernel.<anonymous> (default.js:917)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at push.YC29.__awaiter (default.js:5)
    at DefaultKernel._handleCommOpen (default.js:909)
    at DefaultKernel.<anonymous> (default.js:1016)
(anonymous) @ default.js:132
manager-base.js:281 Could not instantiate widget
(anonymous) @ manager-base.js:281
utils.js:125 Error: Could not create a model.
    at promiseRejection (utils.js:125)
promiseRejection @ utils.js:125
default.js:924 Exception opening new comm
(anonymous) @ default.js:924
default.js:132 Module itk-jupyter-widgets, semver range ^0.16.3 is not registered as a widget module
(anonymous) @ default.js:132
default.js:924 Exception opening new comm
(anonymous) @ default.js:924
default.js:132 Error: Object 'jupyter.widget' not found in registry
    at default.js:1472
    at new Promise (<anonymous>)
    at Object.loadObject (default.js:1451)
    at DefaultKernel.<anonymous> (default.js:917)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at push.YC29.__awaiter (default.js:5)
    at DefaultKernel._handleCommOpen (default.js:909)
    at DefaultKernel.<anonymous> (default.js:1016)
(anonymous) @ default.js:132
lab:1 Uncaught (in promise) Module itk-jupyter-widgets, semver range ^0.16.3 is not registered as a widget module
renderer.js:45 Error displaying widget
renderer.js:46 Module itk-jupyter-widgets, semver range ^0.16.3 is not registered as a widget module
```

**Comment by jxchen01** [comment]
Aha... I switched back to itkwidgets==0.16.1 
No more error then. 

I also tested itkwidgets==0.16.2. It works fine. 

So, some changes from 0.16.2 to 0.16.3 breaks the jupyterlab support.

**Comment by hjmjohnson** [comment]
@jxchen01 Thanks for the diagnosis.  This helped me a lot.  I was running into a similar situation.

**Comment by thewtex** [comment]
@jxchen01 @hjmjohnson thanks for speaking up and the details. It looks like the *itk-jupyter-widgets* never got [published to npmjs.com](https://www.npmjs.com/package/itk-jupyter-widgets) for 0.16.3. It now published -- please try again :-).
