### ISSUE TITLE
JupyterLab 1.0.0+ unsupported - Right?

### ISSUE THREAD

**Issue by consideRatio** [InsightSoftwareConsortium/itk-jupyter-widgets#155]
First of all, thank you for this really mindbogglingly cool project!

I've upgraded to JupyterLab 1.0.1 and found that this JupyterLab extension fails to run properly. I have not yet tried the 0.17.0 version but I'm quite confident that the issue remains.

### The installation of the JLab extension seems ok

```
$ jupyter labextension list
        ...
        itk-jupyter-widgets v0.16.3  enabled  OK
        ...
```

### But using it to show a widget fails

![image](https://user-images.githubusercontent.com/3837114/61069070-cc423f80-a40b-11e9-9916-64b41c29d093.png)

### The issue seems to be...

The dependency specification is too specific for JupyterLab 1.0.1, that comes with ´@jupyter-widgets/base` with a version >=2.0.0.

https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/14b4fb2bac06190f438d62cfa52b5eb6b8a630c4/js/package.json#L58

**Comment by thewtex** [comment]
@consideRatio thank you for the kind words and report!

Bumping `@jupyter-widgets/base` in #159
