### ISSUE TITLE
IO PUB Limit exceeded

### ISSUE THREAD

**Issue by dgutman** [InsightSoftwareConsortium/itk-jupyter-widgets#27]
may want to add this to the readme file in case other users have the issue related to IOPUB/data transfer limits in jupyter 

 jupyter notebook --NotebookApp.iopub_data_rate_limit=100000000

**Comment by thewtex** [comment]
@dgutman great, thanks for the information!

When did you observe that this was required? With a large dataset? On a certain platform?

**Comment by thewtex** [comment]
Addressed in  e887dec
