### ISSUE TITLE
WebGL detection 

### ISSUE THREAD

**Issue by VolkerH** [InsightSoftwareConsortium/itk-jupyter-widgets#41]
The ITK widgets run fine for me if I run them in Firefox which (on my machine has WebGL).
If I use a browser that does not have WebGL support, nothing happens at all. 
It would be nice if the widget were able to detect the presence of WebGL support and print a warning message if WebGL is not supported.

**Comment by thewtex** [comment]
We now have a nice error message and pointer on how to get support with #62 

![selection_018](https://user-images.githubusercontent.com/25432/43217948-04264dca-9011-11e8-8b43-93e87a129f70.png)
