### ISSUE TITLE
Choose interpolation mode

### ISSUE THREAD

**Issue by VolkerH** [InsightSoftwareConsortium/itk-jupyter-widgets#42]
I really like the itk widgets and the ability to inspect intensity values.
However, there seems to be a default interpolation mode enabled when zooming in, such that it is not possible to inspect individual voxels/pixels as they become interpolated with neightbouring values. It would be great to have the option to choose nearest neighbour interpolation. (Maybe it is already there and I'm just missing it).

**Comment by thewtex** [comment]
Yes, good idea - we should make it possible to choose between nearest and linear interpolation.

**Comment by thewtex** [comment]
WIP:

- https://github.com/Kitware/vtk-js/pull/739
- https://github.com/Kitware/vtk-js/pull/743

**Comment by VolkerH** [comment]
Thank you very much for taking up my suggestion so quickly!

**Comment by thewtex** [comment]
CC: @fbudin69500

**Comment by thewtex** [comment]
Addressed by #50
