### ISSUE TITLE
Example that allows adding an interactor from ipywidgets

### ISSUE THREAD

**Issue by dgutman** [InsightSoftwareConsortium/itk-jupyter-widgets#57]
I was trying to do the following, but I think because of a collision between the view(ITK) and the way ipywidgets renders the interactor, it's not properly loading the actual JS viewer..

![image](https://user-images.githubusercontent.com/713166/42475389-7c7fdba4-8398-11e8-87d5-35ccd8733b47.png)

so the notebook can load and widget works without addition of an interactor.. in this case I am just randomly grabbing a subject from the HCP data set

![image](https://user-images.githubusercontent.com/713166/42475418-93a59c4c-8398-11e8-9c08-32ed43b5b4f7.png)

However I'd really like to do something like this, where I have a dropdown box (or perhaps multiple dropdown boxes if I want to change modalities from T1 --> T2 -->Something else)

![image](https://user-images.githubusercontent.com/713166/42475439-a50c72e4-8398-11e8-9f25-68785b6a36da.png)

Is this possible?

**Comment by thewtex** [comment]
@dgutman good idea!

An example and support for this was added in #60 .
