### ISSUE TITLE
Widget not displayed on Windows 10 machine

### ISSUE THREAD

**Issue by austinMLB** [InsightSoftwareConsortium/itk-jupyter-widgets#58]
## Summary
After running the "view" command in the "2D ITK Images" example, the expected widget is not displayed.  No output is provided as a result of that block of code.

## Description

I am unable to get itkwidgets’ “view” to display anything on my Windows machine.  The code seems to work OK on my Mac system.  I'm using the “2D ITK Images” example from the itkwidget documentation.  (Note that, from that example, the first “pip” command of the script doesn’t work on my Windows machine, but itk-io is installed, so I believe that is ok.)

Link to script https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/blob/master/examples/2DImage.ipynb

After executing the “view(image)” image nothing displays.  

## Errors in “Console” output for my Edge browser

input MB: 0.038249000000000005
viewer.js (133,9)

output MB: 0.065536
viewer.js (133,9)

compression amount: 0.5836334228515625
viewer.js (136,9)

SCRIPT0: Expected ']'
ZstdDecompress.js (1,1)

Unhandled promise rejection [object Object]
es6.promise.js (110,11)
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      message: "Could not complete the operation due to error 80020101.",
      stack: "Error: Could not complete the operation due to error 80020101.
   at loadEmscriptenModule (http://localhost:8890/nbextensions/itk-jupyter-widgets/itk/WebWorkers/Pipeline.worker.js:12:397)
   at runPipeline (http://localhost:8890/nbextensions/itk-jupyter-widgets/itk/WebWorkers/Pipeline.worker.js:9:665)
   at Anonymous function (http://localhost:8890/nbextensions/itk-jupyter-widgets/itk/WebWorkers/Pipeline.worker.js:9:1214)
   at i (http://localhost:8890/nbextensions/itk-jupyter-widgets/itk/WebWorkers/Pipeline.worker.js:2:2042)
   at o (http://localhost:8890/nbextensions/itk-jupyter-widgets/itk/WebWorkers/Pipeline.worker.js:2:1868)
   at Anonymous function (http://localhost:8890/nbextensions/itk-jupyter-widgets/itk/WebWorkers/Pipeline.worker.js:2:2421)"
   }

## Possibly relevant versions from my environment

ipykernel          4.8.2
ipython            6.4.0
itk-core           4.13.0
itk-io             4.13.0
itkwidgets         0.10.2
jupyter-client     5.2.3
jupyter-core       4.4.0

browser:  Edge

Anaconda:  1.8.7

## Disclaimer
If this is the wrong forum for this question, please let me know.  If you believe this is just my environment, any clues as to the root of the problem would be appreciated.  Thanks.

**Comment by austinMLB** [comment]
In case this is helpful, if I downgrade itkwidgets to 0.7.0, the error goes away.
Of the versions I tried, 0.7.0 was the newest release which did not exhibit the problem.

**Comment by thewtex** [comment]
@austinMLB Thanks for the detailed report! What browser and browser version are you using on Windows?

**Comment by austinMLB** [comment]
I re-tested this in the same anaconda environment I had used before, and everything seemed to work with the 0.10.2 version of itkwidgets.  My best guess would be that some Windows and/or Edge update , in the past few weeks, resolved the issue.  Regardless, I seem to be getting the correct behavior now.  Thanks.

**Comment by thewtex** [comment]
Great! Thanks for sharing the update :+1:
