### ISSUE TITLE
TypeError: wrap() missing 1 required positional argument: 'widget'

### ISSUE THREAD

**Issue by DoraSzasz** [InsightSoftwareConsortium/itk-jupyter-widgets#6]
I am getting the following error when I try to run the notebook in the examples:

![screen shot 2018-02-16 at 1 31 53 pm](https://user-images.githubusercontent.com/5504833/36325605-f447defc-131d-11e8-806a-d95d645ccafa.png)

Any suggestions?

Thank you!

**Comment by thewtex** [comment]
Hi @DoraSzasz,

What `ipywidgets` version do you have? Try

```
import ipywidgets
print(ipywidgets.__version__)
```

**Comment by thewtex** [comment]
@DoraSzasz In 0.4.0, the required version of `ipywidgets` was bumped, so

```
python -m pip install --upgrade itkwidgets
```

Hopefully fixes your issue. If not, please re-open :-) Thanks!

**Comment by Princessa9639** [comment]
wtf is that I don`t what happend
