### ISSUE TITLE
Default parameters are constantly used when calling view widget

### ISSUE THREAD

**Issue by take5v** [InsightSoftwareConsortium/itk-jupyter-widgets#90]
Hi,

When I run "SpecifyAColormap" example and try execute the last cell:
```
# It is also possible to set the desired colormap when creating the viewer with the `cmap` keyword argument
# Variables for common colormaps are available at itkwidgets.cm.*
view(image, gradient_opacity=0.5, cmap=itkwidgets.cm.bone, annotations=False, ui_collapsed=True)
```
I get this https://imgur.com/a/JwWbKOj

So, default parameters are applied instead of specified parameters.

Tried on Mac and Ubuntu on Firefox. Python 3.6, ipywidgets 7.4.2, itkwidgets 0.13.2.

**Comment by thewtex** [comment]
Hi @take5v,

Thanks for the report.

Do you observe the same behavior with the Binder server?

  https://mybinder.org/v2/gh/InsightSoftwareConsortium/itk-jupyter-widgets/master?filepath=examples/SpecifyAColormap.ipynb

**Comment by take5v** [comment]
Hi @thewtex,

Yes, I got the same result with Binder.

**Comment by thewtex** [comment]
@take5v Thanks -- I was able to reproduce the behavior. It appears to be linked initialization of the viewer in Firefox.
